package org.itson.banco.presentacion;

import java.math.BigDecimal;
import org.itson.banco.dtos.NuevaCuentaDTO;
import org.itson.banco.entidades.Cliente;
import org.itson.banco.negocio.IClientesBO;
import org.itson.banco.negocio.ICuentasBO;
import org.itson.banco.negocio.NegocioException;

/**
 * Ventana de la interfaz gráfica que permite a un cliente autenticado
 * registrar una nueva cuenta bancaria en el sistema.
 * Esta clase interactúa directamente con la capa de persistencia a través de
 * la interfaz ICuentasDAO para procesar la creación de la cuenta.
 * @author Dario
 */
public class AltaCuentaFrame extends javax.swing.JFrame {
    
    /** Cliente que ha iniciado sesión y será el titular de la nueva cuenta. */
    private Cliente clienteLogueado;
    /** Referencia al objeto de acceso a datos para operaciones de cuentas. */
    private ICuentasBO cuentasBO;
    
    private IClientesBO clientesBO;
    
    /**
     * Constructor que inicializa los componentes de la interfaz y recibe las 
     * dependencias de negocio necesarias para la operación.
     * @param cliente El cliente titular que está operando el sistema.
     * @param cuentasBO Implementación de la lógica de negocio para cuentas.
     * @param clientesBO Implementación de la lógica de negocio para clientes.
     */
    public AltaCuentaFrame(Cliente cliente, ICuentasBO cuentasBO, IClientesBO clientesBO) {
        initComponents();
        this.clienteLogueado = cliente;
        this.cuentasBO = cuentasBO;
        this.clientesBO = clientesBO;
    }
    
    /**
     * Realiza validaciones primarias de campos vacíos y formato numérico. Posteriormente, 
     * empaqueta la información en un NuevaCuentaDTO y delega la ejecución a 
     * la capa de negocio. En caso de éxito, notifica al usuario y redirige a la 
     */
    private void crear() {
        try {
            // 1. Validar que los campos no estén vacíos
            if (txtNombre.getText().trim().isEmpty() || txtNombre1.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                        "Por favor, llene todos los campos.", 
                        "Campos vacíos", 
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 2. Extraer datos (txtNombre: número de cuenta, txtNombre1: saldo)
            String numeroCuenta = txtNombre.getText().trim();
            BigDecimal saldoInicial = new BigDecimal(txtNombre1.getText().trim());

            // Validación de negocio: El saldo no puede ser negativo
            if (saldoInicial.compareTo(BigDecimal.ZERO) < 0) {
                 javax.swing.JOptionPane.showMessageDialog(this, "El saldo inicial no puede ser negativo.");
                 return;
            }

            // 3. Empaquetar datos en el DTO
            NuevaCuentaDTO nuevaCuenta = new NuevaCuentaDTO();
            nuevaCuenta.setNumeroCuenta(numeroCuenta);
            nuevaCuenta.setSaldo(saldoInicial);

            // 4. Delegar la persistencia al DAO
            cuentasBO.crearCuenta(nuevaCuenta, clienteLogueado);

            javax.swing.JOptionPane.showMessageDialog(this, "¡Cuenta creada exitosamente!");

            // 5. Navegación: Regresar a la selección de cuentas
            this.regresar();

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El saldo debe ser un número válido.");
        } catch (NegocioException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }

    /**
     * Regresa a la pantalla de selección de cuentas (ElegirCuentaFrame).
     */
    private void regresar(){
        ElegirCuentaFrame selector = new ElegirCuentaFrame(this.clienteLogueado, this.cuentasBO, this.clientesBO);
        selector.setVisible(true);
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lbl3 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 244, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl1.setText("Alta Cuenta");
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 20, -1, -1));

        lbl2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl2.setText("Numero de cuenta:");
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 70, -1, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 120, 488, -1));

        lbl3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl3.setText("Saldo de la cuenta:");
        jPanel1.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 176, -1, -1));

        txtNombre1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 226, 202, -1));

        btnCrear.setBackground(new java.awt.Color(204, 159, 243));
        btnCrear.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        btnCrear.setText("Crear Cuenta");
        btnCrear.addActionListener(this::btnCrearActionPerformed);
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 293, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(217, 217, 217));
        btnRegresar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        btnRegresar.setText("<-");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        crear();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        regresar();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    // End of variables declaration//GEN-END:variables
}
