/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.banco.presentacion;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.itson.banco.entidades.Cliente;
import org.itson.banco.entidades.Cuenta;
import org.itson.banco.persistencia.ITransferenciaDAO;
import org.itson.banco.persistencia.PersistenciaException;
import org.itson.banco.persistencia.TransferenciaDAO;

/**
 *
 * @author Dario
 */
public class ElegirCuentaFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ElegirCuentaFrame.class.getName());
    private final Cliente clienteLogueado;
    private final ITransferenciaDAO transferenciaDAO;

    /**
     * Creates new form ElegirCuentaFrame
     */
    public ElegirCuentaFrame(Cliente cliente, ITransferenciaDAO dao) {
        this.clienteLogueado = cliente;
        this.transferenciaDAO = dao;
        initComponents();
        String nombreCompleto = cliente.getNombres() + " " + cliente.getApellidoPaterno();
        this.lbl2.setText(nombreCompleto);     
        this.llenarTablaCuentas();
    }
    
    private void llenarTablaCuentas() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) tbl.getModel();
            modelo.setRowCount(0);

            List<Cuenta> listaCuentas = transferenciaDAO.consultarCuentasPorCliente(clienteLogueado.getId());

            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");

            for (Cuenta cuenta : listaCuentas) {
                Object[] fila = {
                    cuenta.getNumeroCuenta(),
                    "$" + cuenta.getSaldo(),
                    sdf.format(cuenta.getFechaApertura().getTime())
                };
                modelo.addRow(fila);
            }
        } catch (PersistenciaException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar las cuentas bancarias.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        pnlTable = new javax.swing.JPanel();
        scrTabla = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        lbl2 = new javax.swing.JLabel();
        btnAvanzar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(249, 244, 244));

        lbl1.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        lbl1.setText("Selector de Cuentas Bancarias");

        pnlTable.setBackground(new java.awt.Color(0, 0, 0));

        scrTabla.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        tbl.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero de Cuenta", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.setRowHeight(40);
        scrTabla.setViewportView(tbl);

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrTabla)
                .addContainerGap())
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl2.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        lbl2.setText("Nombre del Cliente");

        btnAvanzar.setBackground(new java.awt.Color(204, 159, 243));
        btnAvanzar.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        btnAvanzar.setText("Avanzar");
        btnAvanzar.addActionListener(this::btnAvanzarActionPerformed);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(lbl1))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lbl2))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGap(355, 355, 355)
                                .addComponent(btnAvanzar)))
                        .addGap(0, 145, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl1)
                .addGap(41, 41, 41)
                .addComponent(lbl2)
                .addGap(18, 18, 18)
                .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAvanzar)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        avanzar();
    }//GEN-LAST:event_btnAvanzarActionPerformed

    private void avanzar(){
        int filaSeleccionada = tbl.getSelectedRow();
            if (filaSeleccionada == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione una cuenta de la tabla.");
                return;
            }

            String numCuenta = tbl.getValueAt(filaSeleccionada, 0).toString();

            MenuClienteFrame siguientePantalla = new MenuClienteFrame(clienteLogueado, transferenciaDAO, numCuenta);
            siguientePantalla.setVisible(true);

            this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            ITransferenciaDAO dao = new TransferenciaDAO();

            Cliente clienteSimulado = new Cliente();
            clienteSimulado.setId(1); 

            new ElegirCuentaFrame(clienteSimulado, dao).setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JScrollPane scrTabla;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
