package org.itson.banco.presentacion;

import javax.swing.JOptionPane;
import org.itson.banco.entidades.Cliente;
import org.itson.banco.negocio.IClientesBO;
import org.itson.banco.negocio.ICuentasBO;
import org.itson.banco.negocio.NegocioException;


/**
 * Ventana de la interfaz gráfica destinada a la captura y validación de la cuenta destino.
 * Esta clase actúa como el primer filtro en el proceso de transferencia, realizando 
 * validaciones sintácticas (formato) y semánticas (existencia en la base de datos) 
 * antes de proceder al ingreso del monto.
 * @author Dario
 */
public class IngresarDestinatarioTransferenciaFrame extends javax.swing.JFrame {
    
    private Cliente clienteLogueado;
    private final ICuentasBO cuentasBO;
    private final IClientesBO clientesBO;
    private String numCuenta;

    /**
     * Constructor que inicializa los componentes y mantiene el contexto operativo.
     * Establece la conexión entre el cliente autenticado, la cuenta de origen 
     * seleccionada y las capas de negocio necesarias para validar la existencia 
     * de cuentas en pasos posteriores.
     * @param clienteLogueado El titular de la cuenta que mantiene la sesión activa.
     * @param cuentasBO Implementación de la lógica de negocio para la gestión de cuentas.
     * @param numCuenta Identificador único de la cuenta de origen (emisor).
     * @param clientesBO Implementación de la lógica de negocio para la gestión de clientes.
     */
    public IngresarDestinatarioTransferenciaFrame(Cliente clienteLogueado, ICuentasBO cuentasBO, String numCuenta, IClientesBO clientesBO) {
        initComponents();
        this.clienteLogueado = clienteLogueado;
        this.cuentasBO = cuentasBO;
        this.numCuenta = numCuenta; 
        this.clientesBO = clientesBO; 
        this.setLocationRelativeTo(null);
    }
    
    /**
     * Cierra la ventana actual y regresa al menú principal de la cuenta de origen.
     */
    public void regresar(){
        MenuCuentaFrame menu = new MenuCuentaFrame(this.clienteLogueado, this.cuentasBO, this.numCuenta, this.clientesBO);
        menu.setVisible(true);
        this.dispose();
    }
    
    /**
     * Realiza las validaciones de la cuenta destino.
     * Verifica que:
     * 1. El campo no esté vacío.
     * 2. El destino no sea la misma cuenta de origen.
     * 3. Cumpla con el estándar de 16 dígitos.
     * 4. La cuenta exista físicamente en los registros del banco.
     */
    public void siguiente(){
        String cuentaDestino = this.txtNumDestinatario.getText().trim();
        
        // Validación: Campo obligatorio
        if (cuentaDestino.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese una cuenta.");
            return;
        }

        // Validación: Regla de negocio (Auto-transferencia prohibida en este flujo)
        if (cuentaDestino.equals(this.numCuenta)) {
            JOptionPane.showMessageDialog(this, "No puedes transferirte a la misma cuenta de origen.");
            return;
        }
        
        // Validación: Formato bancario
        if (cuentaDestino.length() != 16){
            JOptionPane.showMessageDialog(this, "El número de cuenta debe ser de 16 dígitos.");
            return; // Añadido return para evitar que siga el proceso si el formato es incorrecto
        }

        try {
            // Validación: Existencia en BD
            if (cuentasBO.existeCuenta(cuentaDestino)) {
                IngresarSaldoTransferenciaFrame siguiente = new IngresarSaldoTransferenciaFrame(
                    this.clienteLogueado, 
                    this.cuentasBO, 
                    this.numCuenta,
                    cuentaDestino,
                    this.clientesBO
                );
                siguiente.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "La cuenta destino no existe en el sistema.", "Cuenta no encontrada", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error técnico al consultar la cuenta. Intente más tarde.");
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        btnSiguiente = new javax.swing.JButton();
        txtNumDestinatario = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(249, 244, 244));

        btnSiguiente.setBackground(new java.awt.Color(204, 159, 243));
        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        txtNumDestinatario.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        txtNumDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumDestinatarioActionPerformed(evt);
            }
        });

        lbl1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        lbl1.setText("Numero de cuenta del destinatario");

        btnRegresar.setBackground(new java.awt.Color(217, 217, 217));
        btnRegresar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        btnRegresar.setText("<-");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lbl1))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(txtNumDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btnSiguiente))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lbl1)
                .addGap(18, 18, 18)
                .addComponent(txtNumDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnSiguiente)
                .addGap(134, 134, 134))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumDestinatarioActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        siguiente();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        regresar();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel lbl1;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtNumDestinatario;
    // End of variables declaration//GEN-END:variables
}
