/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.banco.presentacion;

import java.math.BigDecimal;
import javax.swing.JOptionPane;
import org.itson.banco.entidades.Cliente;
import org.itson.banco.persistencia.ITransferenciaDAO;
import org.itson.banco.persistencia.PersistenciaException;

/**
 *
 * @author PC
 */
public class IngresarSaldoTransferenciaFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IngresarSaldoTransferenciaFrame.class.getName());

    private Cliente clienteLogueado;
    private ITransferenciaDAO transferenciaDAO;
    private String numCuenta;
    private String numCuentaDestino;
    

    public IngresarSaldoTransferenciaFrame(Cliente clienteLogueado, ITransferenciaDAO transferenciaDAO, String numCuentaOrigen, String numCuentaDestino) {
        initComponents();
        this.clienteLogueado = clienteLogueado;
        this.transferenciaDAO = transferenciaDAO;
        this.numCuenta = numCuentaOrigen;
        this.numCuentaDestino = numCuentaDestino;
        
        try {
            BigDecimal saldo = transferenciaDAO.consultarSaldoCuenta(numCuentaOrigen);
            this.lblSaldoDisponible.setText("$ " + saldo.toString());
        } catch (PersistenciaException ex) {
            this.lblSaldoDisponible.setText("Error");
        }
    }
    
    private void validarYFinalizar() {
        String montoStr = this.txtSaldoaIngresar.getText().trim();

        try {
            BigDecimal monto = new BigDecimal(montoStr);

            if (monto.compareTo(BigDecimal.ZERO) <= 0) {
                JOptionPane.showMessageDialog(this, "El monto debe ser mayor a cero.");
                return;
            }

            BigDecimal saldoActual = transferenciaDAO.consultarSaldoCuenta(this.numCuenta);
            if (saldoActual.compareTo(monto) < 0) {
                JOptionPane.showMessageDialog(this, "Saldo insuficiente para realizar la transferencia.");
                return;
            }

            ConfirmacionTransferenciaFrame confirmacion = new ConfirmacionTransferenciaFrame(
                this.clienteLogueado,
                this.transferenciaDAO,
                this.numCuenta,
                this.numCuentaDestino,
                monto
            );
            confirmacion.setVisible(true);
            this.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un monto numérico válido.");
        } catch (PersistenciaException e) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos.");
            e.printStackTrace();
        }
    }
    
    private void regresar() {
        IngresarDestinatarioTransferenciaFrame anterior = new IngresarDestinatarioTransferenciaFrame(
            this.clienteLogueado, 
            this.transferenciaDAO, 
            this.numCuenta
        );
        anterior.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lblSaldoDisponible = new javax.swing.JLabel();
        txtSaldoaIngresar = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        lblSaldo = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Numero de cuenta del destinatario");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(249, 244, 244));

        lbl1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        lbl1.setText("Cantidad a transferir");

        lblSaldoDisponible.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        lblSaldoDisponible.setText("Saldo Disponible:");

        txtSaldoaIngresar.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        txtSaldoaIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoaIngresarActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(204, 159, 243));
        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        lblSaldo.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        lblSaldo.setText("Aqui se pondra el saldo");

        btnRegresar.setBackground(new java.awt.Color(217, 217, 217));
        btnRegresar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        btnRegresar.setText("<-");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar)
                        .addGap(100, 100, 100)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl1)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(lblSaldoDisponible))))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(btnSiguiente))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSaldo)
                            .addComponent(txtSaldoaIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lbl1))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar)))
                .addGap(18, 18, 18)
                .addComponent(txtSaldoaIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSaldoDisponible)
                .addGap(18, 18, 18)
                .addComponent(lblSaldo)
                .addGap(49, 49, 49)
                .addComponent(btnSiguiente)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSaldoaIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoaIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoaIngresarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        regresar();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        validarYFinalizar();
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldoDisponible;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtSaldoaIngresar;
    // End of variables declaration//GEN-END:variables
}
