package org.itson.banco.presentacion;

import javax.swing.JOptionPane;
import org.itson.banco.entidades.Cliente;
import org.itson.banco.negocio.CuentasBO;
import org.itson.banco.negocio.IClientesBO;
import org.itson.banco.negocio.ICuentasBO;
import org.itson.banco.negocio.NegocioException;
import org.itson.banco.persistencia.CuentasDAO;

/**
 * Pantalla de inicio de sesión (Login) de la aplicación bancaria.
 * Esta clase es responsable de capturar las credenciales del usuario y 
 * coordinar con la capa de negocio IClientesBO para autenticar 
 * al cliente. Si la autenticación es exitosa, inicializa el flujo principal 
 * del banco enviando el objeto Cliente a las pantallas subsecuentes.
 * @author Dario
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /** Dependencia de la capa de negocio para la gestión de clientes. */
    private final IClientesBO clientesBO;
    
    /**
     * Constructor que inyecta el Business Object de clientes.
     * @param clientesBO Interfaz de la lógica de negocio de clientes.
     */
    public LoginFrame(IClientesBO clientesBO) {
        this.clientesBO = clientesBO;
        initComponents();
        this.setLocationRelativeTo(null); // Centrar en pantalla
    }
    
    /**
     * Redirige al usuario a la pantalla de registro de nuevos clientes.
     */
    public void registrarse(){
        RegistroForm Registro = new RegistroForm(this.clientesBO);
        Registro.setVisible(true);
        this.dispose();
    }
    
    /**
     * Procesa el intento de inicio de sesión.
     * Extrae el nombre y la contraseña (manejada como char[] por seguridad),
     * valida que no estén vacíos y solicita la autenticación a la capa BO.
     * En caso de éxito, transfiere el control a la selección de cuentas.
     */
    private void siguiente() {
        String nombreCompleto = txtNombre.getText().trim();
        // El uso de getPassword() es más seguro que getText() para contraseñas
        String contraseña = new String(txtContraseña.getPassword());

        // 1. Validación básica de UI
        if (nombreCompleto.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Debe ingresar su nombre completo y contraseña", 
                "Campos Incompletos", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 2. Intento de autenticación mediante la capa de Negocio
            // El BO se encarga de comparar hashes y buscar en la base de datos
            Cliente cliente = clientesBO.iniciarSesion(nombreCompleto, contraseña);

            // 3. Feedback positivo al usuario
            JOptionPane.showMessageDialog(this, "¡Bienvenido de nuevo, " + cliente.getNombres() + "!");

            // 4. Inyección de dependencias para la siguiente etapa
            ICuentasBO cuentasBO = new CuentasBO(new CuentasDAO());
            
            // Pasamos el objeto 'cliente' (sesión) a la siguiente pantalla
            ElegirCuentaFrame elegir = new ElegirCuentaFrame(cliente, cuentasBO, this.clientesBO);
            elegir.setVisible(true);
            
            // Cerramos el login
            this.dispose();

        } catch (NegocioException ex) {
            // Manejo de credenciales inválidas o fallos de red reportados por el BO
            JOptionPane.showMessageDialog(this, 
                ex.getMessage(), 
                "Error de Acceso", 
                JOptionPane.ERROR_MESSAGE);
            logger.warning("Intento de login fallido para: " + nombreCompleto);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(249, 244, 244));

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl1.setText("LOGIN");

        lbl2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl2.setText("Nombre Completo:");

        lbl3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl3.setText("Contraseña:");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNombre.addActionListener(this::txtNombreActionPerformed);

        btnSiguiente.setBackground(new java.awt.Color(204, 159, 243));
        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(this::btnSiguienteActionPerformed);

        btnRegistrarse.setBackground(new java.awt.Color(204, 159, 243));
        btnRegistrarse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(this::btnRegistrarseActionPerformed);

        txtContraseña.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl1)
                .addGap(259, 259, 259))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                            .addComponent(lbl3)
                            .addComponent(lbl2)
                            .addComponent(txtContraseña)))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(btnSiguiente))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnRegistrarse)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl1)
                .addGap(38, 38, 38)
                .addComponent(lbl2)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl3)
                .addGap(18, 18, 18)
                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnRegistrarse)
                .addGap(18, 18, 18)
                .addComponent(btnSiguiente)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        siguiente();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        registrarse();
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
