/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.banco.presentacion;

/**
 *
 * @author Dario
 */
public class MenuClienteFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuClienteFrame.class.getName());

    /**
     * Creates new form MenuClienteForm
     */
    public MenuClienteFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlRegresar = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        pnlInfoCuenta = new javax.swing.JPanel();
        lblNombreCliente = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lblNumCuenta = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lblSaldoCuenta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnTranferir = new javax.swing.JButton();
        btnRetiro50 = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        pnlPrincipal.setBackground(new java.awt.Color(249, 244, 244));

        btnRegresar.setText("Añadir la flechita de regreso");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout pnlRegresarLayout = new javax.swing.GroupLayout(pnlRegresar);
        pnlRegresar.setLayout(pnlRegresarLayout);
        pnlRegresarLayout.setHorizontalGroup(
            pnlRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegresarLayout.createSequentialGroup()
                .addComponent(btnRegresar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlRegresarLayout.setVerticalGroup(
            pnlRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegresarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnRegresar)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        lblNombreCliente.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        lblNombreCliente.setText("LBL DONDE SE PONDRA EL NOMBRE DEL CLIENTE AL INICIAR SECION");

        lbl1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl1.setText("Numero de cuenta:");

        lblNumCuenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNumCuenta.setText("LBL DONDE SE PONDRA EL NUMERO DE CUENTA");

        lbl2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl2.setText("Saldo disponible:");

        lblSaldoCuenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSaldoCuenta.setText("LBL EL SALDO DISPONIBLE");

        javax.swing.GroupLayout pnlInfoCuentaLayout = new javax.swing.GroupLayout(pnlInfoCuenta);
        pnlInfoCuenta.setLayout(pnlInfoCuentaLayout);
        pnlInfoCuentaLayout.setHorizontalGroup(
            pnlInfoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCliente)
                    .addComponent(lbl1)
                    .addComponent(lblSaldoCuenta)
                    .addComponent(lbl2)
                    .addComponent(lblNumCuenta))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        pnlInfoCuentaLayout.setVerticalGroup(
            pnlInfoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreCliente)
                .addGap(18, 18, 18)
                .addComponent(lbl1)
                .addGap(18, 18, 18)
                .addComponent(lblNumCuenta)
                .addGap(18, 18, 18)
                .addComponent(lbl2)
                .addGap(18, 18, 18)
                .addComponent(lblSaldoCuenta)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        btnTranferir.setBackground(new java.awt.Color(204, 159, 243));
        btnTranferir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTranferir.setText("Transferir");
        btnTranferir.addActionListener(this::btnTranferirActionPerformed);

        btnRetiro50.setBackground(new java.awt.Color(204, 159, 243));
        btnRetiro50.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRetiro50.setText("Retiro sin cuenta");
        btnRetiro50.addActionListener(this::btnRetiro50ActionPerformed);

        btnHistorial.setBackground(new java.awt.Color(204, 159, 243));
        btnHistorial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHistorial.setText("Historial");
        btnHistorial.addActionListener(this::btnHistorialActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTranferir)
                        .addGap(503, 503, 503))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRetiro50)
                        .addGap(469, 469, 469))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHistorial)
                        .addGap(504, 504, 504))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTranferir)
                .addGap(18, 18, 18)
                .addComponent(btnRetiro50)
                .addGap(18, 18, 18)
                .addComponent(btnHistorial)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInfoCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(pnlRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlInfoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnTranferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTranferirActionPerformed

    private void btnRetiro50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiro50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetiro50ActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuClienteFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRetiro50;
    private javax.swing.JButton btnTranferir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNumCuenta;
    private javax.swing.JLabel lblSaldoCuenta;
    private javax.swing.JPanel pnlInfoCuenta;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlRegresar;
    // End of variables declaration//GEN-END:variables
}
