package org.itson.banco.presentacion;

import java.math.BigDecimal;
import org.itson.banco.entidades.Cliente;
import org.itson.banco.negocio.ClientesBO;
import org.itson.banco.negocio.IClientesBO;
import org.itson.banco.negocio.ICuentasBO;
import org.itson.banco.negocio.ITransferenciasBO;
import org.itson.banco.negocio.NegocioException;
import org.itson.banco.negocio.TransferenciasBO;
import org.itson.banco.persistencia.ICuentasDAO;
import org.itson.banco.persistencia.ITransferenciasDAO;
import org.itson.banco.persistencia.PersistenciaException;
import org.itson.banco.persistencia.TransferenciasDAO;

/**
 * Ventana de gestión de una cuenta bancaria específica.
 * Proporciona al cliente una interfaz para visualizar el saldo actual de la cuenta 
 * seleccionada y acceder a las operaciones de transferencias, retiros sin cuenta 
 * y consulta de historial de movimientos.
 * @author Dario
 */
public class MenuCuentaFrame extends javax.swing.JFrame {
    
    private Cliente clienteLogueado;
    private final ICuentasBO cuentasBO;
    private final IClientesBO clientesBO;
    private String numCuenta;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuCuentaFrame.class.getName());

    /**
     * Constructor que inicializa el menú de gestión para una cuenta determinada.
     * @param clienteLogueado Objeto Cliente que mantiene la sesión activa.
     * @param cuentasBO Implementación de la lógica de negocio para operaciones de cuentas.
     * @param numCuenta Identificador único (número de cuenta) de la cuenta a gestionar.
     * @param clientesBO Implementación de la lógica de negocio para operaciones de clientes.
     */
    public MenuCuentaFrame(Cliente clienteLogueado, ICuentasBO cuentasBO, String numCuenta, IClientesBO clientesBO) {
        initComponents();
        this.clienteLogueado = clienteLogueado;
        this.cuentasBO = cuentasBO;
        this.numCuenta = numCuenta;
        this.clientesBO = clientesBO;
        prepararVista();
    }
    
    /**
     * Configura los elementos visuales de la ventana.
     * Este método concatena el nombre completo del titular para el encabezado y 
     * realiza una petición a la capa de negocio ICuentasBO para recuperar 
     * el saldo disponible más reciente, manejando posibles excepciones de conexión.
     */
    private void prepararVista() {
        // Concatenación de nombre completo para el encabezado
        String nombre = clienteLogueado.getNombres() + " "
                + clienteLogueado.getApellidoPaterno() + " "
                + clienteLogueado.getApellidoMaterno();
        lblNombreCliente.setText(nombre);
        lblNumCuenta.setText(numCuenta);
        
        // Consulta de saldo en tiempo real
        try {
            BigDecimal saldo = cuentasBO.consultarSaldoCuenta(numCuenta);
            lblSaldoCuenta.setText("$ " + saldo.toString());
        } catch (NegocioException e) {
            logger.warning("No se pudo recuperar el saldo de la cuenta: " + numCuenta);
            lblSaldoCuenta.setText("Saldo no disponible");
        }
    }
    
    /**
     * Regresa a la pantalla de selección de cuentas (ElegirCuentaFrame).
     */
    private void regresar(){
        ElegirCuentaFrame selector = new ElegirCuentaFrame(this.clienteLogueado, this.cuentasBO, this.clientesBO);
        selector.setVisible(true);
        this.dispose();
    }
    
    /**
     * Inicia el flujo de transferencia bancaria.
     * Navega hacia la captura del destinatario, pasando las dependencias 
     * necesarias para mantener el contexto de la transacción.
     */
    private void transferir(){
        IngresarDestinatarioTransferenciaFrame siguiente = new IngresarDestinatarioTransferenciaFrame(this.clienteLogueado, this.cuentasBO, this.numCuenta, this.clientesBO);
        siguiente.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlInfoCuenta = new javax.swing.JPanel();
        lblNombreCliente = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lblNumCuenta = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lblSaldoCuenta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnHistorial = new javax.swing.JButton();
        btnRetiro50 = new javax.swing.JButton();
        btnTranferir = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        pnlPrincipal.setBackground(new java.awt.Color(249, 244, 244));

        pnlInfoCuenta.setBackground(new java.awt.Color(249, 244, 244));

        lblNombreCliente.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        lblNombreCliente.setText("LBL DONDE SE PONDRA EL NOMBRE DEL CLIENTE AL INICIAR SECION");

        lbl1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl1.setText("Numero de cuenta:");

        lblNumCuenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNumCuenta.setText("LBL DONDE SE PONDRA EL NUMERO DE CUENTA");

        lbl2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl2.setText("Saldo disponible:");

        lblSaldoCuenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSaldoCuenta.setText("LBL EL SALDO DISPONIBLE");

        javax.swing.GroupLayout pnlInfoCuentaLayout = new javax.swing.GroupLayout(pnlInfoCuenta);
        pnlInfoCuenta.setLayout(pnlInfoCuentaLayout);
        pnlInfoCuentaLayout.setHorizontalGroup(
            pnlInfoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCliente)
                    .addComponent(lbl1)
                    .addComponent(lblSaldoCuenta)
                    .addComponent(lbl2)
                    .addComponent(lblNumCuenta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInfoCuentaLayout.setVerticalGroup(
            pnlInfoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreCliente)
                .addGap(18, 18, 18)
                .addComponent(lbl1)
                .addGap(18, 18, 18)
                .addComponent(lblNumCuenta)
                .addGap(18, 18, 18)
                .addComponent(lbl2)
                .addGap(18, 18, 18)
                .addComponent(lblSaldoCuenta)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(249, 244, 244));

        btnHistorial.setBackground(new java.awt.Color(204, 159, 243));
        btnHistorial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHistorial.setText("Historial");
        btnHistorial.addActionListener(this::btnHistorialActionPerformed);

        btnRetiro50.setBackground(new java.awt.Color(204, 159, 243));
        btnRetiro50.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRetiro50.setText("Retiro sin cuenta");
        btnRetiro50.addActionListener(this::btnRetiro50ActionPerformed);

        btnTranferir.setBackground(new java.awt.Color(204, 159, 243));
        btnTranferir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTranferir.setText("Transferir");
        btnTranferir.addActionListener(this::btnTranferirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTranferir)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRetiro50)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHistorial)
                        .addGap(158, 158, 158))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTranferir)
                .addGap(18, 18, 18)
                .addComponent(btnRetiro50)
                .addGap(18, 18, 18)
                .addComponent(btnHistorial)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        btnRegresar.setBackground(new java.awt.Color(217, 217, 217));
        btnRegresar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        btnRegresar.setText("<-");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInfoCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(180, 180, 180))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addGap(21, 21, 21)
                .addComponent(pnlInfoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        regresar();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnTranferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranferirActionPerformed
        transferir();
    }//GEN-LAST:event_btnTranferirActionPerformed

    private void btnRetiro50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiro50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetiro50ActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRetiro50;
    private javax.swing.JButton btnTranferir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNumCuenta;
    private javax.swing.JLabel lblSaldoCuenta;
    private javax.swing.JPanel pnlInfoCuenta;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
