package org.itson.banco.presentacion;

import org.itson.banco.entidades.Cliente;
import org.itson.banco.entidades.Transferencia;
import org.itson.banco.negocio.IClientesBO;
import org.itson.banco.negocio.ICuentasBO;

/**
 * Ventana de resumen y finalización de transferencias.
 * Actúa como un recibo digital que muestra los detalles finales de una operación 
 * exitosa, incluyendo el monto, el ID único de transferencia y la fecha exacta 
 * de la transacción. Esta ventana permite la transición segura de regreso al 
 * menú principal manteniendo el estado de la sesión.
 * @author Dario
 */
public class ResumenTransferenciaFrame extends javax.swing.JFrame {
    private Cliente clienteLogueado;
    private final ICuentasBO cuentasBO; // Agregado
    private final IClientesBO clientesBO;
    private String numCuenta;
    private Transferencia transferenciaAMostrar;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ResumenTransferenciaFrame.class.getName());

    /**
     * Constructor que inicializa el resumen con los datos de la transferencia recién creada.
     * @param clienteLogueado El cliente que mantiene la sesión activa.
     * @param transferencia El objeto de entidad que contiene los datos persistidos en la base de datos.
     * @param cuentasBO Interfaz de la lógica de negocio para la gestión de cuentas.
     * @param clientesBO Interfaz de la lógica de negocio para la gestión de clientes.
     */
    public ResumenTransferenciaFrame(Cliente clienteLogueado, Transferencia transferencia, ICuentasBO cuentasBO, IClientesBO clientesBO) {
        initComponents();
        this.clienteLogueado = clienteLogueado;
        this.transferenciaAMostrar = transferencia;
        this.cuentasBO = cuentasBO;
        this.clientesBO = clientesBO;
        this.numCuenta = transferencia.getNumero_Cuenta();
        this.setLocationRelativeTo(null);
        
        prepararRecibo();
    }
    
    /**
     * Extrae los datos del objeto transferencia y los asigna a los componentes visuales.
     * Muestra el monto con formato de moneda, el ID de transferencia generado por la 
     * base de datos y utiliza java.text.SimpleDateFormat para presentar 
     * la estampa de tiempo de forma legible para el usuario.
     */
    private void prepararRecibo() {
        this.lblMontoTransferido.setText("$ " + transferenciaAMostrar.getMonto().toString());
        this.lblNumTransferencia.setText(String.valueOf(transferenciaAMostrar.getId_transferencia()));
        
        // Formato de fecha y hora para el ticket
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        this.lblFechaOp.setText(sdf.format(transferenciaAMostrar.getFechaHora().getTime()));
    }
    
    /**
     * Finaliza el flujo de la operación y redirige al menú principal.
     * Inyecta las dependencias necesarias (BOs) a la siguiente ventana MenuCuentaFrame
     * para asegurar que el saldo actualizado sea consultado correctamente mediante la 
     * capa de negocio.
     */
    public void continuar(){
        // Regresamos al menú con el saldo ya actualizado gracias a la persistencia del paso anterior
        MenuCuentaFrame siguientePantalla = new MenuCuentaFrame(this.clienteLogueado, this.cuentasBO, this.numCuenta, this.clientesBO);
        siguientePantalla.setVisible(true);
        dispose();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMontoTransferido = new javax.swing.JLabel();
        lblNumTransferencia = new javax.swing.JLabel();
        lblFechaOp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(249, 244, 244));

        jPanel2.setBackground(new java.awt.Color(249, 244, 244));

        btnConfirmar.setBackground(new java.awt.Color(204, 159, 243));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnConfirmar.setText("Continuar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Monto transferido :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Numero de transferencia :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Fecha y hora de la operacion : ");

        lblMontoTransferido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMontoTransferido.setText("AAAAAAAAAAAA");

        lblNumTransferencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumTransferencia.setText("AAAAAAAAA");

        lblFechaOp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaOp.setText("AAAAAAAAAAAAA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblMontoTransferido))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel3)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(lblFechaOp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(lblNumTransferencia)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblMontoTransferido)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblNumTransferencia)
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblFechaOp)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Resumen de transferencia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(111, 111, 111))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnConfirmar)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmar)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        continuar();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblFechaOp;
    private javax.swing.JLabel lblMontoTransferido;
    private javax.swing.JLabel lblNumTransferencia;
    // End of variables declaration//GEN-END:variables

}
